# Generated by Django 2.0.4 on 2018-04-20 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('device_numbers', models.CharField(max_length=255, null=True, verbose_name='推播裝置代碼')),
                ('sys_type', models.CharField(max_length=45, verbose_name='系統識別')),
                ('phone_number', models.CharField(max_length=45, verbose_name='電話號碼')),
            ],
        ),
        migrations.CreateModel(
            name='OrgUnits',
            fields=[
                ('org_code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='組織單位代碼')),
                ('org_type', models.CharField(choices=[('edu', '學校、教育單位'), ('idv', '個人、教師、獨立使用')], help_text='ex: edu, idv, com', max_length=10, verbose_name='組織單位類型')),
                ('country', models.CharField(choices=[('tw', '臺灣')], help_text='ex: tw, us', max_length=10, verbose_name='國家')),
                ('abbreviation', models.CharField(help_text='ex: ntub', max_length=50, verbose_name='單位縮寫')),
                ('name', models.CharField(help_text='臺北商業大學', max_length=100, verbose_name='組織單位名稱')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='學生使用者id')),
                ('department', models.CharField(max_length=50, verbose_name='科系')),
                ('edu_type', models.CharField(max_length=45, verbose_name='學制')),
                ('edu_year', models.CharField(help_text='西元年', max_length=45, verbose_name='入學年')),
                ('team_type', models.CharField(max_length=45, null=True, verbose_name='組別')),
                ('id_number', models.CharField(max_length=50, verbose_name='學號')),
                ('class_number', models.CharField(max_length=20, verbose_name='班級號碼')),
                ('unit_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.OrgUnits', verbose_name='所屬單位')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='教師使用者id')),
                ('department', models.CharField(max_length=50, verbose_name='科系')),
                ('time_case', models.CharField(max_length=20, null=True, verbose_name='專兼任')),
                ('job_title', models.CharField(default='老師', max_length=45, verbose_name='職務名稱')),
                ('unit_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.OrgUnits', verbose_name='所屬單位')),
            ],
        ),
        migrations.AddField(
            model_name='registertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
