# Generated by Django 2.0.4 on 2018-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunits',
            name='country',
            field=models.CharField(choices=[('tw', '臺灣')], default='tw', help_text='ex: tw, us', max_length=10, verbose_name='國家'),
        ),
    ]
