# Generated by Django 2.0.4 on 2018-04-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_orgunits_created_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfo',
            old_name='id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='user',
        ),
    ]
