# Generated by Django 2.0.4 on 2018-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180428_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunits',
            name='name',
            field=models.CharField(help_text='ex:臺北商業大學', max_length=100, verbose_name='組織單位名稱'),
        ),
    ]
