# Generated by Django 2.0.4 on 2018-05-02 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180430_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunits',
            name='org_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
