version: "3"
services:
  db:
    container_name: rcp_postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123@Admin
      POSTGRES_USER: rcp
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

  django:
    container_name: rcp_django
    build: .
    volumes:
      - django-log:/usr/src/app/log/
      - django-media:/usr/src/app/media/
      - django-assets:/usr/src/app/assets/
      - django-static:/usr/src/app/static/
    environment:
      DJANGO_ENV: master
    depends_on:
      - db

  web:
    container_name: rcp_nginx
    image: nginx:1.13.2-alpine
    restart: always
    volumes:
      - django-media:/usr/src/app/media/
      - django-static:/usr/src/app/static/:ro
      - django-assets:/usr/src/app/assets/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/app/ssl:/etc/nginx/ssl/:ro
    ports:
      - 8000:8000
    depends_on:
      - django


volumes:
  django-log:
  django-media:
  django-static:
  django-assets:
  pgdata:
