# Generated by Django 2.0.4 on 2018-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_auto_20180503_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('endDate', models.DateTimeField(verbose_name='結束日期')),
                ('postDate', models.DateTimeField(auto_now_add=True, verbose_name='張貼日期')),
                ('postTarget', models.ManyToManyField(null=True, to='curriculum.Subjects', verbose_name='公告目標')),
            ],
        ),
    ]
