# Generated by Django 2.1.1 on 2018-10-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_created_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='postDate',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='postTarget',
            new_name='post_target',
        ),
    ]
