# Generated by Django 2.1.1 on 2018-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20181020_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(verbose_name='結束日期'),
        ),
    ]
