# Generated by Django 2.0.4 on 2018-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('canNotify', models.BooleanField(default=False, verbose_name='是否需要通知')),
            ],
        ),
    ]
