# Generated by Django 2.0.4 on 2018-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_seal',
            field=models.BooleanField(default=False, verbose_name='是否封存'),
        ),
    ]
