# Generated by Django 2.0.4 on 2018-05-02 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_auto_20180430_2105'),
        ('account', '0006_orgunits_org_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_id', models.CharField(max_length=50, verbose_name='beacon 名稱')),
                ('beacon_uuid', models.UUIDField(default=uuid.uuid4)),
                ('beacon_major', models.IntegerField()),
                ('beacon_minor', models.IntegerField()),
                ('is_manual', models.BooleanField(default=False, verbose_name='是否手動')),
                ('curriculum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Subjects', verbose_name='課程')),
            ],
        ),
        migrations.CreateModel(
            name='RollCallCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.TimeField(auto_now_add=True)),
                ('check_date', models.DateField(auto_now_add=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roll_call.Beacon', verbose_name='iBeacon')),
                ('section_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Section_Time', verbose_name='節次')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student', verbose_name='學生')),
            ],
        ),
        migrations.CreateModel(
            name='RollCallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(default='到課', max_length=50, verbose_name='假別，曠課，到課')),
                ('record_date', models.DateField(verbose_name='日期')),
                ('section_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Section_Time', verbose_name='節次')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student', verbose_name='學生')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='beacon',
            unique_together={('beacon_uuid', 'beacon_major', 'beacon_minor')},
        ),
    ]
