# Generated by Django 2.0.4 on 2018-04-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20180430_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('weak', models.IntegerField(verbose_name='星期')),
                ('section', models.IntegerField(verbose_name='節次')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('year', models.CharField(max_length=15, verbose_name='學年')),
                ('semester', models.CharField(max_length=10, null=True, verbose_name='學期')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否進行中')),
                ('subjects_members', models.ManyToManyField(to='account.Student', verbose_name='課程參與人')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Teacher', verbose_name='課程教師')),
            ],
        ),
        migrations.AddField(
            model_name='section_time',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Subjects', verbose_name='科目'),
        ),
    ]
