# Generated by Django 2.0.4 on 2018-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180430_0430'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='subjects_members',
        ),
        migrations.AddField(
            model_name='subjects',
            name='members',
            field=models.ManyToManyField(to='account.Student', verbose_name='課程參與人'),
        ),
    ]
