# Generated by Django 2.0.4 on 2018-05-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roll_call', '0001_initial'),
        ('curriculum', '0002_auto_20180430_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section_Time',
            new_name='SectionTime',
        ),
    ]
