# Generated by Django 2.0.4 on 2018-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20180503_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='class_room',
            field=models.CharField(blank=True, max_length=15, verbose_name='教室'),
        ),
    ]
