# Generated by Django 2.0.4 on 2018-05-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_subjects_class_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiontime',
            name='subjects_name',
        ),
        migrations.AlterUniqueTogether(
            name='sectiontime',
            unique_together={('subjects', 'weak', 'section')},
        ),
    ]
